### PR TITLE
Add option to spatially propagate only the observations of a specific variable.

### PR DESCRIPTION
**Pull request by mmazzolini**
Hi @ealonsogzl, @krisaalstad,

I've tried to do experiment with joint assimilation of fSCA from S2 and ICESat-2.
I don't think it makes any sense (both in terms of efficiency, and in statistical terms) to spatially propagate fSCA as they are spatially distributed. 
Hence I tried to add the possibility for the user to select the variables whose observations you want to spatially propagate.
In the config.py file, I added a var_to_prop variable.
 if set to false, var_to_prop = var_to_assim.
Otherwise, the var_to_prop variable is used in the modules/spatial_MuSA.get_neig_info() function to select only neighbouring observations of the variables we want to propagate. 

Let me know if you think this makes sense. My first simulations seem okay. Let me know if you think I have to modify smthing else.

Cheers,
Marco,

### CODE REVIEW

**Comment by ealonsogzl** [comment]
Good idea @mmazzolini , this is an interesting option. I think it is a good idea to perform spatial propagation, even if the variable to be assimilated is well distributed spatially. This can help you to smooth out the effect of some outliers. It becomes particularly relevant if you are able to map the uncertainty correctly, for example from the Sun-sensor-topography geometry. But this is of course expensive.

If this PR works well, it is a good way to limit the computational cost, and provides more control to what is done. Anyway, I think it would be necessary to make some modification in the obs_mask function, so that the generated mask only maps the variables that you want to propagate spatially, otherwise the computational cost will remain the same because MuSA will search in all the cells in what we call in the code the "neighborhood" (all the cells close to the cell where you are performing the analysis). 

Wouldn't it be like that?

**Comment by mmazzolini** [comment]
Hei @ealonsogzl,

I experienced already a performance improvement with this, as I was trying to propagate spatially more than 10 fSCA observations: that would have taken days. I cannot quantify that, but can make some tests.

For modifying the obs_mask function with only the observations on the variable to propagate: can you think of any drawback on doing that? I will try to do it this afternoon.

Cheers,
Marco.

**Comment by ealonsogzl** [comment]
By modifying the `obs_mask()` function, the difference should be quite big, I think. 
Now MuSA will try to open a lot of files that don't really have any observations, so it will not use them at all. This works like this for each cell:

1. We generate a mask that tells us where there are observations (`obs_mask()`).
2. Later, we use this mask to generate a list of filenames to read (`create_neigb()`), which are the names of the files in our 'neig'.
3. We loop (`get_neig_info()`) opening all these files. At each iteration, `if np.isnan(obs).all()`, nothing is done and it continue to the next ensemble file in neig.

This forces a lot of unnecessary files to be opened if you are not propagating all observations or if the observation mask is not very precise (as happens now if the number of seasons increase).

In fact, it might be cleaner and easier to maintain to change this logic completely. We could put a flag in the name of the intermediate ensembles indicating whether they contain observations or not. This way only the files of the cells with observations will be opened,just by adding a `try/except` to [this line](https://github.com/ealonsogzl/MuSA/blob/055d4b95528636c76a7d2158bf3d3e1d22fe0daa/modules/spatialMuSA.py#L748). It will be also very useful in simulations of several years, because the number of cells in each neighborhood will adapt to the availability of observations, so the computational cost will be adaptive... fancy stuff :)

We could avoid the creation of the obs_mask also.

Doing so would be easy (I think). just modify the ensemble names a bit in create_ensemble_cell() and spatial_assim(), adding an *_obs.* to each name in case there are observations. Something like:

```
# in create_ensemble_cell()
name_ensemble = "{step}_{j}it_ensbl_{lat}_{lon}_{obs}.pkl.blp".\
    format(step=step-1,
        j=cfg.Kalman_iterations - 1,
        lat=lat_idx,
        lon=lon_idx,
        obs=obs_flag)
```
I think even wait_for_ensembles() should work thanks to the wildcard notation. We should be carefull with the name at the last IES iteration to allow `collect_results()` to work.


btw, remember that for testing purposes the simple model is much cheaper to run.

**Comment by ealonsogzl** [comment]
I forget this PR. I will merge it now

**Pull request merged**
